### ISSUE TITLE
Could not locate the assemply "DriveInfoEx". And other critical errors

### ISSUE THREAD

**Issue by jlndk** [davidfrp/LabyOS#2]
Can't compile because Visual studio throws 3 errors (2 warnings, and one critical error to be precise).

![screenshot 23](https://cloud.githubusercontent.com/assets/3009101/8140931/eb0cf83e-1160-11e5-96ab-49a26708b23a.png)

I dont know if it's because im on Windows 10, or just need something fixed

**Comment by davidfrp** [comment]
The reference 'DriveInfoEx' was used in the older versions of LabyOS and is not used any longer. You can safely remove the reference without causing damage. The error 'Unable to find minifest signing cartificate in the cartificate store.' is because i dont have a certificate (certificates are used too make an application trustworthy). I will fix this critical error soon.

**Comment by davidfrp** [comment]
Tak! Jeg har besvaret dig inde på GitHub.

Ps. her downloads til .NET Frameworket: http://blogs.msdn.com/b/dotnet/p/dotnet_sdks.aspx





Fra: Jonas Lindenskov Nielsen
Sendt: ‎lørdag‎, ‎13‎. ‎juni‎ ‎2015 ‎00‎:‎13
Til: davidfrp/LabyOS





Can't compile because Visual studio throws 3 errors (2 warnings, and one critical error to be precise).

 screenshot 23
